# Generated by Django 3.2.6 on 2021-09-17 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spanishVersion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='program',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='secretary',
            old_name='phoneNumber',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='program',
            name='secretary_fk',
        ),
        migrations.AddField(
            model_name='program',
            name='respSecretary',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='respSecretary', to='spanishVersion.secretary'),
            preserve_default=False,
        ),
    ]
