# Generated by Django 3.2.9 on 2021-11-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spanishVersion', '0002_auto_20210917_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('creation', models.CharField(max_length=64)),
                ('grade', models.CharField(max_length=64)),
                ('profile', models.TextField()),
                ('objective', models.TextField()),
                ('atuation', models.TextField()),
                ('system', models.CharField(max_length=64)),
                ('durationMin', models.IntegerField()),
                ('durationMax', models.IntegerField()),
                ('shiftVacancies', models.CharField(max_length=64)),
                ('language', models.CharField(max_length=64)),
                ('contact', models.CharField(max_length=64)),
            ],
        ),
    ]
