# Generated by Django 3.2.9 on 2021-11-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spanishVersion', '0003_graduationprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduationprogram',
            name='durationMax',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='graduationprogram',
            name='durationMin',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='graduationprogram',
            name='language',
            field=models.CharField(default='Portuguesa', max_length=64),
        ),
    ]
