# Generated by Django 3.2.9 on 2021-11-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spanishVersion', '0004_auto_20211112_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('center', models.CharField(max_length=64)),
                ('reference', models.CharField(max_length=64)),
                ('profile', models.TextField()),
                ('monthCost', models.IntegerField()),
                ('duration', models.IntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name='PostStricto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('center', models.CharField(max_length=64)),
                ('reference', models.CharField(max_length=64)),
                ('degree', models.CharField(max_length=64)),
                ('creation', models.CharField(max_length=64)),
                ('profile', models.TextField()),
                ('capes', models.IntegerField()),
                ('concentration', models.CharField(max_length=64)),
            ],
        ),
    ]
